#!/bin/bash

# Test de diagnostic pour les problèmes MediaDetailScreen
echo "🧪 Diagnostic MediaDetailScreen - Problème d'affichage"
echo "====================================================="

echo "🐛 Problèmes identifiés:"
echo "   1. Text strings must be rendered within a <Text> component"
echo "   2. Le mauvais film est affiché dans la vue détail"

echo ""
echo "✅ Corrections apportées:"
echo ""
echo "📝 1. Correction du rendu de texte:"
echo "   - Ajout de la fonction safeText() pour convertir en string"
echo "   - Correction des propriétés qui retournent des nombres"
echo "   - Gestion sécurisée des valeurs null/undefined"

echo ""
echo "🔍 2. Diagnostic pour le mauvais film:"
echo "   - Ajout de logs détaillés dans loadMediaDetails()"
echo "   - Logs dans extractTmdbId() pour tracer l'ID"
echo "   - Vérification des données passées depuis RoomScreen"
echo "   - Fallback sur les données de base si pas de TMDB ID"

echo ""
echo "🧪 Pour diagnostiquer:"
echo "   1. Démarrer l'app mobile avec les logs activés"
echo "   2. Aller dans une room avec des médias"
echo "   3. Cliquer sur un média"
echo "   4. Vérifier les logs dans la console:"
echo "      - [MediaDetailScreen] Media reçu: ..."
echo "      - [extractTmdbId] Media reçu: ..."
echo "      - [MediaDetailScreen] TMDB ID extrait: ..."

echo ""
echo "🎯 Questions à vérifier:"
echo "   - Les données Media de la room ont-elles un tmdbId correct ?"
echo "   - Le tmdbId correspond-il au bon film ?"
echo "   - Y a-t-il une confusion entre l'ID local et l'ID TMDB ?"
echo "   - Les détails TMDB récupérés correspondent-ils au film attendu ?"

echo ""
echo "📱 Test manual:"
echo "   1. cd mobile && npm start"
echo "   2. Ouvrir les logs de développement"
echo "   3. Naviguer vers une room"
echo "   4. Cliquer sur un média connu"
echo "   5. Vérifier que le titre affiché correspond au média cliqué"
echo "   6. Si ce n'est pas le cas, vérifier les logs pour tracer le problème"
